version: '3.9'

services:
  db:
    image: postgres:13.4
    ports:
      - "5432:5432"
    env_file:
      - social_network/.env
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - .:/docker-entrypoint-initdb.d
      - ./logs:/var/log
    restart: always
  web:
    build: ./social_network
    depends_on:
      - db
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - social_network/.env
    volumes:
      - ./social_network:/social_network/
      - static:/static
    command: sh -c "python3 setup.py install --user && uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000"
  redis:
    image: "redis:alpine"
    restart: always
    container_name: "redis"

    command: sh -c "redis-server --port $${REDIS_PORT}"
    ports:
      - "5370:6379"
#    expose:
#      - "echo $${REDIS_PORT}"

    env_file:
      - social_network/.env
  celery-worker:
    build: ./social_network
    env_file:
      - social_network/.env
    depends_on:
      - redis
      - web
    volumes:
      - ./social_network:/social_network/
    command: celery -A core.celery worker -E --loglevel=info

  celery-beat:
    build: ./social_network
    env_file:
      - social_network/.env
    depends_on:
      - redis
      - web
    volumes:
      - ./social_network:/social_network/
    command: celery -A core.celery beat --loglevel=info


  flower:
    build: ./social_network
    command: celery -A core.celery flower
    volumes:
      - ./social_network:/social_network/
    ports:
      - "8585:5555"
    env_file:
      - ./social_network/.env
    depends_on:
      - celery-worker
      - redis

volumes:
  pgdata:
  static:
  app:
