version: '3.9'

services:
  db:
    image: postgres:13.4
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - .:/docker-entrypoint-initdb.d
      - ./logs:/var/log
    restart: always
  web:
    build: apps/
    depends_on:
      - db
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - apps/:/code/
      - static:/static
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000

volumes:
  pgdata:
  static:
  app:
