"""Dislikwe added

Revision ID: 0853d16cb038
Revises: 6be95406f04d
Create Date: 2023-01-21 18:09:20.875214

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0853d16cb038'
down_revision = '6be95406f04d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dislike',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('post_id', sa.Integer(), nullable=False),
                    sa.Column('owner_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
                    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dislike')
    # ### end Alembic commands ###
