"""likes_count

Revision ID: 6be95406f04d
Revises: f06a312dcba2
Create Date: 2023-01-20 21:33:47.645566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6be95406f04d'
down_revision = 'f06a312dcba2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
