"""deleted bool fields added

Revision ID: d25587f521b7
Revises: 0853d16cb038
Create Date: 2023-03-13 23:24:50.359172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd25587f521b7'
down_revision = '0853d16cb038'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('posts', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'deleted')
    op.drop_column('comment', 'deleted')
    # ### end Alembic commands ###
