"""changed

Revision ID: efce7b89f5b3
Revises: d7af450f4ee3
Create Date: 2023-01-17 00:09:28.227660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efce7b89f5b3'
down_revision = 'd7af450f4ee3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
